name: github_demo

on:
  push:
      branches: main
      
  workflow_dispatch: 

jobs:
    build:
      runs-on: ubantu-latest

      steps:
        - uses: actions/checkout@v4.2.2
        
        - name: run sample github
          run: echo "starting run"
        
      
